CREATE TABLE owners (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    owner_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL
);

CREATE TABLE dogs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    breed VARCHAR(255) NOT NULL,
    owner_phone VARCHAR(255) NOT NULL,
    dog_name VARCHAR(255) NOT NULL
);
